TR-585 lisätään esimerkkivastaussanoma
FinnishCustoms-SuomenTulli/account-register-information-query pull request #55
Opened 2020-03-24 13:29 UTC by PaavoKaltiainen

2020-03-25 08:23 UTC, extMalinEsk commented on examples/example_response.xml
> +												<ns:Cd>Y</ns:Cd>
Tämä tulee muuttumaan COID:ksi, pitäisikö mergetä vasta siinä yhteydessä?

2020-03-26 14:06 UTC, ext-alexpeltonen commented on examples/example_response.xml
> +												<ns:Cd>Y</ns:Cd>
Minusta voisi päivittää jo etupainotteisesti tähän pullaan -> COID

2020-03-30 08:52 UTC, ext-alexpeltonen requested changes

2020-03-30 08:52 UTC, ext-alexpeltonen commented on examples/example_response.xml
> +				<ns:BizMsgIdr xmlns:ns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01">J4ZRcxvfQnaZ7rv/yuQdjw==</ns:BizMsgIdr>
riittää tehdä tämä namepacen asettaminen vain kerran

2020-03-30 12:42 UTC, ext-alexpeltonen approved these changes

2020-03-30 12:43 UTC, merged