TR-202 Kyselyrajapinnan esimerkki-XML
FinnishCustoms-SuomenTulli/account-register-information-query pull request #6
Opened 2019-09-26 13:11 UTC by PaavoKaltiainen

Added example xml files

2019-09-30 10:13 UTC, ext-timovakeva approved these changes

2019-09-30 11:03 UTC, ext-attelaine approved these changes

2019-10-01 07:03 UTC, ext-alexpeltonen requested changes

2019-10-01 07:03 UTC, ext-alexpeltonen commented on examples/henkilotodistuksen_tunnistenumero.xml
> +								<ns1:Cd>COID</ns1:Cd>
muuttunut, käytetään "Y"

2019-10-01 07:03 UTC, ext-alexpeltonen commented on examples/henkilotodistuksen_tunnistenumero.xml
> +						<ns2:Cd>OWNE</ns2:Cd>
-> "ALLP"

2019-10-01 07:03 UTC, ext-alexpeltonen commented on examples/henkilotodistuksen_tunnistenumero.xml
> +								<ns1:Cd>COID</ns1:Cd>
tiketöity tarvittava korjaus rajapintakuvaukseen https://jira.tulli.csc.fi/browse/TR-260

2019-10-01 10:59 UTC, ext-alexpeltonen approved these changes

2019-10-01 10:59 UTC, merged