TR-937 Update WSDL
FinnishCustoms-SuomenTulli/account-register-information-query pull request #96
Opened 2020-09-22 12:07 UTC by ext-alexpeltonen

2020-09-23 08:29 UTC, extMalinEsk approved these changes

2020-09-23 09:56 UTC, MikkoKarhunsuo requested changes
Muutos pitäisi tehdä myös examples -hakemiston esimerkkisanomiin.

2020-09-25 06:00 UTC, MikkoKarhunsuo commented on examples/Query_example-IBAN.xml
>                              <X509Data>
X509Data ja X509Certificate kahteen kertaan.

2020-09-25 11:04 UTC, ext-alexpeltonen commented on examples/Query_example-IBAN.xml
>                              <X509Data>
Korjattu

2020-09-30 08:54 UTC, MikkoKarhunsuo approved these changes

2021-08-04 14:39 UTC, closed without merging