Tr 933: English MD version of the query interface documentation
FinnishCustoms-SuomenTulli/account-register-information-query pull request #99
Opened 2020-09-30 15:48 UTC by extMalinEsk

2020-10-01 05:40 UTC, ext-attelaine commented on index_en.md
> +|Kiistanalainen|auth.002|Supplementary Data in accordance with [the disputed schema](schemas/disputed.xsd)|
Nämä jääneet kääntämättä

2020-10-01 05:41 UTC, ext-attelaine commented on index_en.md
> +|FIN002|InformationResponseFIN002|auth.002.001.01|Sisältää Includes the details of safe-deposit boxes corresponding to the search parameters|
"Sisältää" pois

2020-10-01 05:44 UTC, ext-attelaine commented on index_en.md
> +Taulukossa on kuvattu sanoman tietuNoden käyttö.
-> The table describes the use of records in the message.

2020-10-01 05:45 UTC, ext-attelaine commented on index_en.md
> +#### <a name="CustomerAccount1"></a> CustomerAccount1 käyttö
-> Use of

2020-10-01 05:46 UTC, ext-attelaine commented on index_en.md
> +#### AccountRole1 käyttö
-> Use of

2020-10-01 05:46 UTC, ext-attelaine commented on index_en.md
> +#### <a name="SafetyDepositBoxAndParties"></a> SafetyDepositBoxAndParties käyttö
-> Use of

2020-10-01 05:49 UTC, ext-attelaine commented on index_en.md
> +### 1.3 Viittaukset
-> References

2020-10-01 05:50 UTC, ext-attelaine commented on index_en.md
> +### 1.4 General decsription
-> description

2020-10-01 07:13 UTC, extMalinEsk commented
Korjattu puuttuvat käännökset ja virheet sekä ja lisäksi käännetty tietoturvavaatimusdokumentin nimi englanniksi, vaikka sisältö onkin suomeksi (löyty palvelusta haulla sillä nimellä).

2020-10-02 09:09 UTC, MikkoKarhunsuo commented on index_en.md
> +b) the certificate is an NoDAS-approved website identification certificate, the certificate is valid and is not included in the certificate revocation list of party providing the certificate, and the
NoDAS -> eiDAS

2020-10-02 09:13 UTC, MikkoKarhunsuo commented on index_en.md
> +The competent authority contacting the query interface identifies the data supplier or the party authorised by the data supplier with the help of the server certificate. The party authorised by the d
A contact with the... -lause voisi olla oma kappaleensa.

2020-10-02 09:31 UTC, MikkoKarhunsuo commented on index_en.md
> +### <a name="Id-element_usage"></a> Use of 4.11 Id element
Kappaleen numero otsikon sisällä

2020-10-02 09:36 UTC, MikkoKarhunsuo commented on index_en.md
> +b) the server certificate is an NoDAS-approved website identification certificate, the certificate is valid and is not included in the certificate revocation list of party providing the certificate,
NoDAS -> eIDAS

2020-10-02 09:42 UTC, MikkoKarhunsuo commented
Samalla voisi muuttaa index.md:n linkin osoittamaan PDF:n sijasta index_en.md:hen sekä korvata PDF:n sisällön linkillä index_en.md:hen (kun päivitysrajapinnan PDF:ssä tehtiin).

2020-10-02 12:22 UTC, extMalinEsk commented
Tehty korjaukset, päivitetty linkki ja PDF osoittamaan index_en.md:hen.

2020-10-02 12:34 UTC, MikkoKarhunsuo approved these changes

2020-10-05 11:16 UTC, ext-alexpeltonen requested changes

2020-10-05 11:16 UTC, ext-alexpeltonen commented on index_en.md
> +ISO 20022 code set references are used in the messages. The code set references are found at the ISO 20022 page [External Code Sets](https://www.iso20022.org/external_code_list.page).
Pitäisi osoittaa repoon

2020-10-05 11:16 UTC, ext-alexpeltonen commented on index_en.md
> +The query interface of the data retrieval system uses the ISO 20022 messages [InformationRequestOpeningV01 (auth.001.001.01)](https://www.iso20022.org/message/10186/download) and [InformationRequestR
Linkkien pitäisi osoittaa repoon

2020-10-05 11:40 UTC, ext-alexpeltonen approved these changes

2020-10-05 11:41 UTC, merged